server:
  port: ${PORT:8080}
spring:
  application:
    name: Parking
  profiles:
    active: ${ENV:dev}
    web: java -Dserver.port=$PORT -jar target/demo-0.0.1-SNAPSHOT.jar
  datasource:
    url: ${AC_DATABASE_URL:jdbc:mysql://bcda2c13bd582d:f43eed5d@us-cdbr-east-06.cleardb.net/heroku_57a72dd7e131b3d?reconnect=true}
    username: ${AC_DATABASE_USER:bcda2c13bd582d}
    password: ${AC_DATABASE_PWD:f43eed5d}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-parking
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:10.30.1.143}
    port: ${REDIS_PORT:30010}
    password: ${REDIS_PASSWORD:XcwvZ7knqPzn6HaH}
  http:
    multipart:
      enabled: false
  task:
    scheduling:
      pool:
        size: 5
common:
  core:
    open-api:
      servers: ${OPEN_API_SERVER:http://localhost:8080}
    security:
      path-matcher:
        permit-all-path-patterns:
          - /webjars/swagger-ui/**
          - /v3/api-docs/**
          - /swagger-resources/**
          - /webjars/**
          - /swagger-ui/**
          - /swagger-ui.html
          - /null/swagger-resources/**
          - /api/v1/auth/**
          - /api/v1/public/**
          - /api/v1/media/public/**
        permit-all-map:
          GET:
            - /api/v1/languages-support/**
            - /api/v1/translator/**
            - /api/v1/languages/**
      x-api:
        services:
          ai:
            prefixes:
            keys:
              - value: ${AI_X_API_KEY:7d9ed96e-2a7d-11ed-a261-0242ac120002}
                enable: ${AI_X_API_KEY_ENABLE:true}
      cors:
        allowed-origins:
          - ${CORS_ORIGINS:http://localhost:8080}
          - http://localhost:8000
          - https://api-parking-dev.hcm.unicloud.ai/swagger-ui/
        allowed-methods: ${CORS_METHODS:*}
        allowed-headers: ${CORS_HEADERS:*}

      oauth2-resource-server:
        auth:
          jwk-set-uri: ${KEYCLOAK_URI:https://keycloak-hcmute.herokuapp.com}/auth/realms/${PROFILE_REALM:your-tour}/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_URI:https://keycloak-hcmute.herokuapp.com}/auth/realms/${PROFILE_REALM:your-tour}
    client:
      external:
        ai:
          uri: ${AI_API_URI:http://10.30.1.207:30500}
          properties:
            license-plate: ${LICENSE_PLATE:/v1.1.0/license-plate/recognition}
            key: ${KEY:unicloudALPR123654789}

your-tour-profile:
  security:
    keycloak-realms:
      your-tour:
        realm-name: ${PROFILE_REALM:your-tour}
        auth-server-url: ${KEYCLOAK_URI:https://keycloak-hcmute.herokuapp.com}/auth
        client-id: ${PROFILE_CLIENT_ID:your-tour-client}
        client-secret: ${PROFILE_CLIENT_SECRET:fySVcgqO6K2AimvMrFCMuE2Q7slno65H}
        token-uri: ${KEYCLOAK_URI:https://keycloak-hcmute.herokuapp.com}/auth/realms/${PROFILE_REALM:your-tour}/protocol/openid-connect/token
        token-invalidate-uri: ${KEYCLOAK_URI:https://keycloak-hcmute.herokuapp.com}/auth/realms/${PROFILE_REALM:your-tour}/protocol/openid-connect/logout
        user-info-uri: ${KEYCLOAK_URI:https://keycloak-hcmute.herokuapp.com}/auth/realms/${PROFILE_REALM:your-tour}/protocol/openid-connect/userinfo
        credentials:
          secret: ${PROFILE_CLIENT_SECRET:fySVcgqO6K2AimvMrFCMuE2Q7slno65H}
          grant_type: password

keycloak:
  auth-server-url: ${KEYCLOAK_URI:https://keycloak-hcmute.herokuapp.com}/auth
  ssl-required: external
  realm: ${PROFILE_REALM:your-tour}
  resource: ${PROFILE_CLIENT_ID:your-tour-client}
  credentials:
    secret: ${PROFILE_CLIENT_SECRET:fySVcgqO6K2AimvMrFCMuE2Q7slno65H}
  use-resource-role-mappings: true


minio:
  endpoint: ${MINIO_ENDPOINT:http://10.30.1.143:30112}
  accessKey: ${MINIO_ACCESS_KEY:minio}
  secretKey: ${MINIO_SECRET_KEY:kjeThg7UhKt54yu}
  fileHost: ${MINIO_FILE_HOST:https://api-parking-dev.hcm.unicloud.ai/parking-server}
  expiredDefault: ${EXPIRED:60}



